# Generated by Django 4.0.6 on 2022-07-28 09:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('category', '0002_alter_catergory_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='catergory',
            name='slug',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
