# Generated by Django 4.0.6 on 2022-07-28 09:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('category', '0007_alter_catergory_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='catergory',
            name='slug',
            field=models.SlugField(max_length=100, unique=True),
        ),
    ]
